name: generate-snake

on:
  schedule: # 每天自動跑一次
    - cron: "0 0 * * *"
  workflow_dispatch: # 可以手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: slhs1121505
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#aad751,#8ebd6b,#58a15f,#4e7d35,#1e441e

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
